# Generated by Django 6.1.1 on 2026-10-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('prediction', models.CharField(max_length=16)),
                ('model_score', models.DecimalField(decimal_places=4, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'transaction analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
